<a href="https://colab.research.google.com/github/Jahura7/assignment_on_research_design_and_experiment/blob/experiment/experiment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Imports and Loading Dataset**

In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [17]:
df = pd.read_csv('stroke_risk_prediction_dataset.csv')

# **Exploratory Data Analysis**

**STEP 1: SHAPE & STRUCTURAL INTEGRITY CHECK**

In [21]:
print(f"Initial Shape: {df.shape}")

Initial Shape: (50000, 40)

In [22]:
df.head()

,Patient_ID,Age,Gender,Country,Height_cm,Weight_kg,BMI,Blood_Pressure_Systolic,Blood_Pressure_Diastolic,Heart_Rate,...,Medication_Adherence,Exercise_Hours_Per_Week,Daily_Walking_Minutes,Work_Type,Residence_Type,Air_Pollution_Exposure,Stroke_Risk_Score,AI_Health_Recommendation,Doctor_Consultation_Needed,Stroke_Risk
0,1,80.0,Male,China,145.2,69.3,32.9,112,82,109,...,Excellent,NaN,79.0,Retired,Urban,High,47,Exercise Regularly,Yes,Moderate
1,2,37.0,Female,United Kingdom,188.6,110.8,31.1,137,76,59,...,Average,0.6,48.0,Student,Rural,Medium,40,Improve Diet Quality,Yes,Moderate
2,3,85.0,Female,Germany,175.5,103.7,33.7,108,105,89,...,Poor,1.7,114.0,Private,Rural,Medium,76,Monitor Blood Glucose Daily,Yes,High
3,4,44.0,Other,Brazil,161.3,50.2,19.3,126,73,88,...,Poor,1.5,101.0,Retired,Rural,Low,40,Exercise Regularly,Yes,Moderate
4,5,52.0,Female,United States,162.8,103.6,39.1,115,60,70,...,Average,7.1,55.0,Government,Rural,Medium,38,Monitor Blood Pressure,Yes,Moderate

In [23]:
df.tail()

,Patient_ID,Age,Gender,Country,Height_cm,Weight_kg,BMI,Blood_Pressure_Systolic,Blood_Pressure_Diastolic,Heart_Rate,...,Medication_Adherence,Exercise_Hours_Per_Week,Daily_Walking_Minutes,Work_Type,Residence_Type,Air_Pollution_Exposure,Stroke_Risk_Score,AI_Health_Recommendation,Doctor_Consultation_Needed,Stroke_Risk
49995,49996,22.0,Male,Spain,171.7,113.4,38.5,139,78,81,...,Average,3.2,41.0,Government,Urban,Medium,40,Improve Diet Quality,No,Moderate
49996,49997,61.0,Male,South Africa,164.6,64.0,23.6,123,92,87,...,Poor,0.7,92.0,Student,Rural,Medium,59,Reduce Sodium Intake,Yes,Moderate
49997,49998,76.0,Female,Spain,148.9,56.4,25.4,153,93,95,...,Average,0.7,31.0,Retired,Urban,High,64,Improve Diet Quality,Yes,Moderate
49998,49999,31.0,Other,Italy,183.7,75.7,22.4,108,77,76,...,Poor,3.4,90.0,Retired,Rural,Low,26,Continue Regular Exercise,No,Low
49999,50000,45.0,Male,Italy,165.1,123.3,45.2,169,95,96,...,Average,0.5,74.0,Self-Employed,Urban,Medium,51,Exercise Regularly,No,Moderate

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 40 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Patient_ID                    50000 non-null  int64
 1   Age                           49781 non-null  float64
 2   Gender                        50000 non-null  object
 3   Country                       50000 non-null  object
 4   Height_cm                     48475 non-null  float64
 5   Weight_kg                     48477 non-null  float64
 6   BMI                           50000 non-null  float64
 7   Blood_Pressure_Systolic       50000 non-null  int64
 8   Blood_Pressure_Diastolic      50000 non-null  int64
 9   Heart_Rate                    50000 non-null  int64
 10  Blood_Glucose                 49040 non-null  float64
 11  HbA1c                         48994 non-null  float64
 12  Total_Cholesterol             48996 non-null  float64
 13  HDL                           48979 non-null  float64
 14  LDL                           48950 non-null  float64
 15  Triglycerides                 48968 non-null  float64
 16  Smoking_Status                50000 non-null  object
 17  Alcohol_Consumption           50000 non-null  object
 18  Physical_Activity_Level       50000 non-null  object
 19  Sleep_Hours                   48974 non-null  float64
 20  Stress_Level                  50000 non-null  object
 21  Diet_Quality                  50000 non-null  object
 22  Family_History_Stroke         50000 non-null  object
 23  Family_History_Heart_Disease  50000 non-null  object
 24  Diabetes                      50000 non-null  object
 25  Hypertension                  50000 non-null  object
 26  Heart_Disease                 50000 non-null  object
 27  Previous_TIA                  50000 non-null  object
 28  Atrial_Fibrillation           50000 non-null  object
 29  Chronic_Kidney_Disease        50000 non-null  object
 30  Medication_Adherence          48949 non-null  object
 31  Exercise_Hours_Per_Week       48946 non-null  float64
 32  Daily_Walking_Minutes         48949 non-null  float64
 33  Work_Type                     50000 non-null  object
 34  Residence_Type                50000 non-null  object
 35  Air_Pollution_Exposure        50000 non-null  object
 36  Stroke_Risk_Score             50000 non-null  int64
 37  AI_Health_Recommendation      50000 non-null  object
 38  Doctor_Consultation_Needed    50000 non-null  object
 39  Stroke_Risk                   50000 non-null  object
dtypes: float64(13), int64(5), object(22)
memory usage: 15.3+ MB

In [26]:
df.describe()

,Patient_ID,Age,Height_cm,Weight_kg,BMI,Blood_Pressure_Systolic,Blood_Pressure_Diastolic,Heart_Rate,Blood_Glucose,HbA1c,Total_Cholesterol,HDL,LDL,Triglycerides,Sleep_Hours,Exercise_Hours_Per_Week,Daily_Walking_Minutes,Stroke_Risk_Score
count,50000.000000,49781.000000,48475.000000,48477.000000,50000.000000,50000.000000,50000.000000,50000.000000,49040.000000,48994.000000,48996.000000,48979.000000,48950.000000,48968.000000,48974.000000,48946.000000,48949.000000,50000.000000
mean,25000.500000,53.903096,170.125582,87.506141,30.901386,135.061420,84.840620,82.521020,145.031421,7.488103,225.020832,57.661655,140.149685,205.200147,7.005401,5.001214,59.947742,54.782320
std,14433.901067,21.070953,14.484573,24.565490,10.254560,20.526562,14.685149,16.141082,43.405484,1.733379,54.776297,18.718465,46.146752,83.538912,1.731441,2.892267,34.987073,13.996729
min,1.000000,18.000000,145.000000,45.000000,11.900000,100.000000,60.000000,55.000000,70.000000,4.500000,130.000000,25.000000,60.000000,60.000000,4.000000,0.000000,0.000000,2.000000
25%,12500.750000,36.000000,157.600000,66.200000,22.700000,117.000000,72.000000,68.000000,107.400000,6.000000,177.700000,41.500000,100.100000,133.200000,5.500000,2.500000,30.000000,45.000000
50%,25000.500000,54.000000,170.100000,87.500000,30.100000,135.000000,85.000000,83.000000,145.100000,7.500000,224.900000,57.700000,140.200000,205.300000,7.000000,5.000000,60.000000,54.000000
75%,37500.250000,72.000000,182.800000,108.800000,37.800000,153.000000,98.000000,97.000000,182.700000,9.000000,272.400000,73.800000,180.000000,277.600000,8.500000,7.500000,90.000000,64.000000
max,50000.000000,90.000000,195.000000,130.000000,61.500000,170.000000,110.000000,110.000000,220.000000,10.500000,320.000000,90.000000,220.000000,350.000000,10.000000,10.000000,120.000000,100.000000

In [30]:
print(df.dtypes.value_counts)

<bound method IndexOpsMixin.value_counts of Patient_ID                        int64
Age                             float64
Gender                           object
Country                          object
Height_cm                       float64
Weight_kg                       float64
BMI                             float64
Blood_Pressure_Systolic           int64
Blood_Pressure_Diastolic          int64
Heart_Rate                        int64
Blood_Glucose                   float64
HbA1c                           float64
Total_Cholesterol               float64
HDL                             float64
LDL                             float64
Triglycerides                   float64
Smoking_Status                   object
Alcohol_Consumption              object
Physical_Activity_Level          object
Sleep_Hours                     float64
Stress_Level                     object
Diet_Quality                     object
Family_History_Stroke            object
Family_History_Heart_Disease     object
Diabetes                         object
Hypertension                     object
Heart_Disease                    object
Previous_TIA                     object
Atrial_Fibrillation              object
Chronic_Kidney_Disease           object
Medication_Adherence             object
Exercise_Hours_Per_Week         float64
Daily_Walking_Minutes           float64
Work_Type                        object
Residence_Type                   object
Air_Pollution_Exposure           object
Stroke_Risk_Score                 int64
AI_Health_Recommendation         object
Doctor_Consultation_Needed       object
Stroke_Risk                      object
dtype: object>

In [35]:
df.isnull().sum()

Patient_ID                         0
Age                              219
Gender                             0
Country                            0
Height_cm                       1525
Weight_kg                       1523
BMI                                0
Blood_Pressure_Systolic            0
Blood_Pressure_Diastolic           0
Heart_Rate                         0
Blood_Glucose                    960
HbA1c                           1006
Total_Cholesterol               1004
HDL                             1021
LDL                             1050
Triglycerides                   1032
Smoking_Status                     0
Alcohol_Consumption                0
Physical_Activity_Level            0
Sleep_Hours                     1026
Stress_Level                       0
Diet_Quality                       0
Family_History_Stroke              0
Family_History_Heart_Disease       0
Diabetes                           0
Hypertension                       0
Heart_Disease                      0
Previous_TIA                       0
Atrial_Fibrillation                0
Chronic_Kidney_Disease             0
Medication_Adherence            1051
Exercise_Hours_Per_Week         1054
Daily_Walking_Minutes           1051
Work_Type                          0
Residence_Type                     0
Air_Pollution_Exposure             0
Stroke_Risk_Score                  0
AI_Health_Recommendation           0
Doctor_Consultation_Needed         0
Stroke_Risk                        0
dtype: int64

In [27]:
print(f"Total Patient Profiles: {df.shape[0]}")

Total Patient Profiles: 50000

In [28]:
print(f"Total Registered Medical Attributes: {df.shape[1]}")

Total Registered Medical Attributes: 40